version: '3.3'
 
#### Nginx Service ####
services: 
 webserver:
    image: nginx:alpine
    container_name: srv-ws-nginx
    labels:
      conteiner.description: "Server Web NGINX"
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d

#### GLPI Service ####

 mysql57:
  image: mysql:5.7
  container_name: 'srv-db-mysql57'
  labels:
     conteiner.description: "Server DataBase Mysql 5.7"
  ports:
     - 3306:3306
  volumes:
     - ./conf/mysql57/mysqld.cnf://etc/mysql/mysql.conf.d/mysqld.cnf:ro
     - ./storage/mysql57/mysqldata:/var/lib/mysql 
  restart: always
  environment:
     - TZ=America/Sao_Paulo
     - MYSQL_ROOT_PASSWORD=glpihml
     - MYSQL_DATABASE=glpi
     - MYSQL_USER=glpiuser
     - MYSQL_PASSWORD=glpipass

 glpi:
  build:
    context: .
    dockerfile: ./conf/glpi/Dockerfile-glpi
    args:
      UBUNTU_VERSION: 16.04
  container_name: 'srv-glpi'
  depends_on:
    - mysql57
  labels:
     conteiner.description: "GLPI Web Server Apache"
  volumes:
    - ./conf/glpi/html:/var/www/html
    - ./conf/glpi/scripts/glpi-start.sh:/opt/glpi-start.sh:ro
  restart: always
  ports:
    - 8001:80
    - 8441:443
  environment:
    - GLPI_VERSION=9.1.3
    - GLPI_MYSQL_HOST=mysql
    - GLPI_MYSQL_USER=glpiuser
    - GLPI_MYSQL_PASS=glpipass
    - GLPI_MYSQL_DB=glpi

 phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  container_name: 'srv-phpmyadmin'
  labels:
     conteiner.description: "PHPmyadmin Webpage"
  ports:
     - 8080:80
  volumes:
     - /storage/glpi/sessions
  restart: always
  environment:
     - TZ=America/Sao_Paulo
     - PMA_HOST=mysql
     - PMA_PORT=3306