version: '3.3'
services: 

#### NGINX WEBSERVER ####
  webserver:
    image: nginx:latest
    container_name: srv-ws-nginx
    labels:
       conteiner.description: "Server Web NGINX"
    hostname: srv-nginx
    restart: always
   ports:
       - "80:80"
       - "443:443"
    links :
       - glpi
       - ocsinv
       - syspass
       - grafana
       - wordpress
       - duplicati
    volumes:
       - ./conf/nginx/conf.d/center.conf:/tmp/template
    

#### APPLICATION GLPI ####
  mysql-glpi:
    image: mysql:5.7.23
    container_name: srv-db-glpi
    labels:
       conteiner.description: "Server DataBase MySQL5.7 FOR GLPI"
    hostname: srv-db-glpi
    restart: always
    ports:
       - "3306:3306"
    volumes:
       - ./storage/mysq-glpi/var/lib/mysql:/var/lib/mysql
    env_file:
       - ./conf/mysql57/mysql-glpi.env

  glpi:
    image: diouxx/glpi
    container_name : srv-glpi
    labels:
       conteiner.description: "Application GLPI"
    hostname: srv-glpi
    restart: always
    ports:
       - "8001:80"
    volumes:
       - /etc/timezone:/etc/timezone:ro
       - /etc/localtime:/etc/localtime:ro
       - ./storage/glpi/:/var/www/html/glpi
    env_file:
       - ./conf/glpi/glpi.env
    depends_on:
         - mysql-glpi
    links :
         - mysql-glpi
         - webserver



#### APPLICATION OCSINVETORY ####       
  mysql-ocsinv:
   image: mysql:5.7.23
   container_name: srv-db-ocsinv
   labels:
      conteiner.description: "Server DataBase MySQL5.7 FOR OCS INVENTORY"
   hostname: srv-db-ocsinv
   restart: always
   ports:
      - "3307:3306"
   volumes:
      - ./storage/mysq-ocsinv/var/lib/mysql:/var/lib/mysql
   env_file:
      - ./conf/mysql57/mysql-ocsinv.env

  ocsinv :
    image : ocsinventory/ocsinventory-docker-image:latest
    container_name : srv-ocs
    labels:
       conteiner.description: "Application OCS INVENTORY"
    hostname: srv-ocsinv
    restart: always
    ports :
      - 8002:80
      - 8442:443
    volumes :
       - ./storage/ocsinv/ocsdownload:/usr/share/ocsinventory-reports/ocsreports/download/
       - ./storage/ocsinv/ocssrv:/etc/ocsinventory-reports/
       - ./storage/ocsinv/ocslib:/var/lib/ocsinventory-reports/
    env_file:
       - ./conf/ocsinv/ocsinv.env
    depends_on:
       - mysql-ocsinv
    links :
       - mysql-ocsinv
       - webserver


#### APPLICATION SYSPASS ####
  mysql-syspass:
   image: mysql:5.7.23
   container_name: srv-db-syspass
   labels:
      conteiner.description: "Server DataBase MySQL5.7 FOR SYSPASS"
   hostname: srv-db-syspass
   restart: always
   ports:
      - "3308:3306"
   volumes:
      - ./storage/mysq-syspass/var/lib/mysql:/var/lib/mysql
   env_file:
      - ./conf/mysql57/mysql-syspass.env

  syspass:
    image: syspass/syspass:3.1.2
    container_name: srv-syspass
    labels:
      conteiner.description: "Application SYSPASS"
    hostname: srv-syspass
    restart: always
    ports:
       - "8003:80"
       - "8443:443"
    links:
       - mysql-syspass
    volumes:
       - ./storage/syspass/syspass-config:/var/www/html/sysPass/app/config
       - ./storage/syspass/syspass-backup:/var/www/html/sysPass/app/backup
    env_file:
       - ./conf/syspass/syspass.env
    depends_on:
       - mysql-syspass
    links :
       - mysql-syspass
       - webserver

#### APPLICATION GRAFANA ####
  grafana:
    image: grafana/grafana:6.5.0    
    container_name: srv-grafana
    labels:
       conteiner.description: "Application GRAFANA"
    hostname: srv-grafana
    restart: always
    ports:
     - 8004:3000
     - 8444:443
    user: "104"
#   volumes:
#     - ./storage/grafana/var/lib:/var/lib/grafana
#     - ./storage/grafana/var/log:/var/log/grafana
#     - ./storage/grafana/:/etc/grafana
    links :
      - webserver

#### APPLICATION WORDPRESS ####
  mysql-wordpress:
    image: mysql:5.7.23
    container_name: srv-db-wordpress
    labels:
       conteiner.description: "Server DataBase MySQL5.7 FOR WORDPRESS"
    hostname: srv-db-wordpress
    restart: always
    ports:
       - "3309:3306"
    volumes:
       - ./storage/mysq-wordpress/var/lib/mysql:/var/lib/mysql
    env_file:
       - ./conf/mysql57/mysql-wordpress.env

  wordpress:
    image: wordpress:latest
    container_name: srv-wordpress
    labels:
       conteiner.description: "Application WORDPRESS"
    hostname: srv-wordpress
    restart: always
    ports:
       - "8005:80"
       - "8445:443"
#    volumes:
#       - ./storage/wordpress/syspass-config:/var/www/html/sysPass/app/config
    env_file:
       - ./conf/wordpress/wordpress.env
    depends_on:
       - mysql-wordpress
    links :
       - mysql-wordpress
       - webserver

#### APPLICATION DUPLICATI ####
  duplicati:
    image: linuxserver/duplicati
    container_name: srv-duplicati
    labels:
      conteiner.description: "Application DUPLICATI"
    hostname: srv-duplicati
    restart: always
    env_file:
      - ./conf/duplicati/duplicati.env
    volumes:
      - .conf/duplicati/config:/config
      - ./storage/duplicati/backups:/backups
      - ./storage/duplicati/source:/source
    ports:
      - 8006:8200
      links :
      - webserver

