version: '3'
services :
  web :
    image : ocsinventory/ocsinventory-docker-image:latest
    container_name : srv-ocsinventory
    environment :
      OCS_DBNAME : ocsweb
      OCS_DBSERVER_READ : ocsinventory-db
      OCS_DBSERVER_WRITE : ocsinventory-db
      OCS_DBUSER : ocs
      OCS_DBPASS : ocs
    volumes :
      - ocsdownload:/usr/share/ocsinventory-reports/ocsreports/download/
      - ocssrv:/etc/ocsinventory-reports/
      - ocslib:/var/lib/ocsinventory-reports/
    links :
      - db
    ports :
      - 8002:80
      - 8444:443

  db :
    image : mysql:5.7
    container_name : srv-ocsinventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : mdp
      MYSQL_USER : ocs
      MYSQL_PASSWORD : ocs
      MYSQL_DATABASE : ocsweb
    volumes :
      - ./sql/:/docker-entrypoint-initdb.d/
      - ocsdata:/var/lib/mysql
    ports :
      - 3306:3306

volumes:
  ocsdata:
    driver: local
  ocssrv:
    driver: local
  ocslib:
    driver: local
  ocsdownload:
    driver: local