version: '2'

services:
  app:
    container_name: srv-syspass-app
    image: syspass/syspass:3.1.0
    restart: always
    ports:
      - "8082:80"
      - "8443:443"
    depends_on:
      - db
    volumes:
      - syspass-config:/var/www/html/sysPass/app/config
      - syspass-backup:/var/www/html/sysPass/app/backup
    environment:
      - USE_SSL=yes
  db:
    container_name: srv-syspass-db
    restart: always
    image: mariadb:10.2
    environment:
      - MYSQL_ROOT_PASSWORD=syspass
    expose:
      - "3306"
    volumes:
      - syspass-db:/var/lib/mysql

volumes:
  syspass-config: {}
  syspass-backup: {}
  syspass-db: {}