version: "3.2"

services:
#Mysql Container
  mysql:
    image: mysql:5.7.23
    container_name: srv-glpi-db
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=glpidb
      - MYSQL_USER=glpi_user
      - MYSQL_PASSWORD=glpi

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name: srv-glpi
    hostname: glpi
    ports:
      - "8001:80"